// <auto-generated />
namespace BilgeKafe.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Urunler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Urunler));
        
        string IMigrationMetadata.Id
        {
            get { return "202109301347538_Urunler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
